version: "3.8"
services:
  pg-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    links:
    - "pg-db:pg-db"
